repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--config-file", "mypy.ini"]
        files: ^src/.*\.py$

  - repo: local
    hooks:
      - id: check-secrets
        name: Check for API keys and secrets
        entry: python3 scripts/check_secrets.py
        language: system
        types: [text]
        pass_filenames: true
